### ISSUE TITLE
Dashboard - Age categories

### ISSUE THREAD

**Issue by yemergy** [nirgn975/WhatsBuzz#12]
![age](https://cloud.githubusercontent.com/assets/17341325/14763490/7dd6d09a-099f-11e6-9b5c-1d0ef4e3bc12.jpg)

**Comment by nirgn975** [comment]
@yemergy And? what will `כללי`  say? Posts with `כללי` will display on all the pages?
I mean, for example, post with `ילדים` category will display random posts with `כללי` and `ילדים` in the section at the right side?

**Comment by yemergy** [comment]
exactly

**Comment by yemergy** [comment]
good job
