### ISSUE TITLE
Dashboard | Facebook name - Font size and color

### ISSUE THREAD

**Issue by yemergy** [nirgn975/WhatsBuzz#14]
![font](https://cloud.githubusercontent.com/assets/17341325/14763562/944afa52-09a1-11e6-9c1f-582bbf0ed8a7.jpg)

**Comment by nirgn975** [comment]
@yemergy It's `live`, check if it works like you expect it to (in the color field you need to enter the `#`, and in the size just the number).

**Comment by nirgn975** [comment]
@yemergy It's working?

**Comment by yemergy** [comment]
@nirgn975 how should I know? its live but its not working yet

**Comment by nirgn975** [comment]
@yemergy yes it is. no?
Try creating a new post, `facebook game` one, and try to get the user name (remember that you need `#` in the color field).

**Comment by yemergy** [comment]
i already did it, but i cant check if it works.
as i said, the fields live, but we cant connect with facebook (yet) to check it.

you want me to close it anyway? are you 100% sure that its working?

**Comment by nirgn975** [comment]
![whatsbuzz](https://cloud.githubusercontent.com/assets/3472902/14847197/084be9d6-0c70-11e6-9084-352004099cdb.png)

You don't see yours?

**Comment by yemergy** [comment]
Good job nigga
