### ISSUE TITLE
Stick the footer to the bottom of the page.

### ISSUE THREAD

**Issue by nirgn975** [nirgn975/WhatsBuzz#16]

**Comment by yemergy** [comment]
dont work too hard on it,
anyway the length of the site will never be short

**Comment by nirgn975** [comment]
Yeah, I opened this issues only because I already know the solution (;

**Comment by yemergy** [comment]
lazy ass motherfucker
and I thought that you are trying to challenge yourself

**Comment by nirgn975** [comment]
LOL
I told you I know how to do it, I only needed some time.
