### ISSUE TITLE
Post content - Contains pieces of code

### ISSUE THREAD

**Issue by yemergy** [nirgn975/WhatsBuzz#166]
![p](https://cloud.githubusercontent.com/assets/17341325/21076265/d9a04e60-bf2f-11e6-9eba-7a06b2f3e78b.jpg)

**Comment by nirgn975** [comment]
Fixed.
![selection_008](https://cloud.githubusercontent.com/assets/3472902/21083137/7e51519e-bff2-11e6-8de0-00e8b7eb9b4f.png)

**Comment by nirgn975** [comment]
Fixed in #159
