### ISSUE TITLE
Retry Button

### ISSUE THREAD

**Issue by yemergy** [nirgn975/WhatsBuzz#168]
אפשר לשנות את האייקון בכפתור
![retry](https://cloud.githubusercontent.com/assets/17341325/21076344/722a0d1e-bf31-11e6-8e29-efbdb522a0c5.jpg)
![retry-png](https://cloud.githubusercontent.com/assets/17341325/21076343/72288fb6-bf31-11e6-9fa1-15c54331aac2.png)

**Comment by yemergy** [comment]
icon:
![retry-png](https://cloud.githubusercontent.com/assets/17341325/21076348/8fcc7816-bf31-11e6-940b-92c903ddaf84.png)

**Comment by nirgn975** [comment]
@yemergy 
I took a different image, because I want an `svg` and not a `png`. Is this good enough?
![selection_007](https://cloud.githubusercontent.com/assets/3472902/21083089/585fa068-bff1-11e6-8106-b1a340eb0694.png)

If it is, close the issue. If not, what need to be fixed?

**Comment by yemergy** [comment]
Change it to this icon:
and make it a bit smaller

https://daks2k3a4ib2z.cloudfront.net/56c73bc0e252235614c16f0a/584dbb9db69c4afe1dfbe9eb_Retry%20SVG.svg

**Comment by nirgn975** [comment]
Fixed in #159
