### ISSUE TITLE
Top menu

### ISSUE THREAD

**Issue by yemergy** [nirgn975/WhatsBuzz#171]
הגובה של הלוגו צריך להיות בגובה של הכפתור
הריווח מעל הכפתור ומתחת לכפתור צריך להיות שווה
כמו פה http://whatsbuzz.webflow.io/

![menu](https://cloud.githubusercontent.com/assets/17341325/21076438/d5fe1752-bf33-11e6-9fd8-b76173f4eb83.jpg)

**Comment by nirgn975** [comment]
@yemergy Like this?
![selection_010](https://cloud.githubusercontent.com/assets/3472902/21083459/c32b19ce-bff9-11e6-8898-4d1506ae445e.png)

**Comment by yemergy** [comment]
Awesome

**Comment by nirgn975** [comment]
It's not too small?

**Comment by yemergy** [comment]
nope,
but align it to the left
![header-logo](https://cloud.githubusercontent.com/assets/17341325/21083487/6db0fd50-bffa-11e6-8a34-1eeb7b6f46e4.jpg)

**Comment by nirgn975** [comment]
![selection_011](https://cloud.githubusercontent.com/assets/3472902/21083537/4835e26a-bffb-11e6-9e7b-a43a07481f2f.png)

Fixed in #159
