### ISSUE TITLE
Stick footer to bottom

### ISSUE THREAD

**Issue by yemergy** [nirgn975/WhatsBuzz#172]
![footer](https://cloud.githubusercontent.com/assets/17341325/21081964/172c75e2-bfda-11e6-8dd1-c602e3b6a1e9.jpg)

**Comment by yemergy** [comment]
תוסיף עוד "פדינג" בתוך הפוטר, שיהיה מרווח שווה מלמעלה למטה 15px
כמו פה: http://whatsbuzz.webflow.io/

**Comment by nirgn975** [comment]
Fixed in #159
