### ISSUE TITLE
Mobile - padding

### ISSUE THREAD

**Issue by yemergy** [nirgn975/WhatsBuzz#173]
אפשר לצמצם את המרווחים בערך ל5 px
![mobile](https://cloud.githubusercontent.com/assets/17341325/21082733/38f95496-bfea-11e6-88b3-6cd8ef15731a.jpg)

**Comment by nirgn975** [comment]
On my local machine there is not posts on the database, but imagine if you need:
![selection_012](https://cloud.githubusercontent.com/assets/3472902/21083646/aa5d0d68-bffd-11e6-9922-d03e2f3e8b28.png)

Fixed in #159
