### ISSUE TITLE
Mobile - Logo + Title size

### ISSUE THREAD

**Issue by yemergy** [nirgn975/WhatsBuzz#174]
להקטין בהרבה את הלוגו, שיהיה בגובה של הריבוע של התפריט.
להקטין את הפונט של הכותרת, שיהיה בגודל של הטקסט שרשום למטה בתוכן הפוסט

![mobile2](https://cloud.githubusercontent.com/assets/17341325/21082766/ba08fbb8-bfea-11e6-86ca-7d96010e17d4.jpg)

**Comment by nirgn975** [comment]
Fixed on #180
