### ISSUE TITLE
Trends posts - Share button

### ISSUE THREAD

**Issue by yemergy** [nirgn975/WhatsBuzz#175]
![share](https://cloud.githubusercontent.com/assets/17341325/21091824/67e95f14-c051-11e6-905b-935389477e8f.jpg)

**Comment by nirgn975** [comment]
Yeah, good that you noticed.
So, in `Facebook-Games` we share the image, and in trends we share the page (with the image of the post, and not the image the user has, because he don't have one here), right?

**Comment by yemergy** [comment]
exactly

**Comment by nirgn975** [comment]
Fixed on #180
