### ISSUE TITLE
Cant add Tags

### ISSUE THREAD

**Issue by yemergy** [nirgn975/WhatsBuzz#177]
![tag](https://cloud.githubusercontent.com/assets/17341325/21150961/7dab483a-c169-11e6-94d5-a0307b4247e1.jpg)
_______________________________________________

![tag2](https://cloud.githubusercontent.com/assets/17341325/21150987/904bedbe-c169-11e6-9c43-807a44fa874e.jpg)

**Comment by nirgn975** [comment]
Solved in #159
