### ISSUE TITLE
*Urgent* Preview image when share post on Facebook

### ISSUE THREAD

**Issue by yemergy** [nirgn975/WhatsBuzz#178]
Where is the cover image, title and subtitle
![sharefb](https://cloud.githubusercontent.com/assets/17341325/21151300/a48cffec-c16a-11e6-8b23-6cbeb80bc811.jpg)

![fb-share](https://cloud.githubusercontent.com/assets/17341325/21151678/0a397892-c16c-11e6-8022-0d984f547643.jpg)

**Comment by nirgn975** [comment]
Fix on #182
