### ISSUE TITLE
Mobile - open menu

### ISSUE THREAD

**Issue by yemergy** [nirgn975/WhatsBuzz#185]
![open-menu](https://cloud.githubusercontent.com/assets/17341325/21242916/4e994436-c31f-11e6-884e-208ea481186e.jpg)

**Comment by nirgn975** [comment]
iPhone 5:
![selection_013](https://cloud.githubusercontent.com/assets/3472902/21398961/38422210-c7b2-11e6-8565-2607b46f1958.png)
