### ISSUE TITLE
Home Page - posts title

### ISSUE THREAD

**Issue by yemergy** [nirgn975/WhatsBuzz#187]
.card[_ngcontent-jks-7] .card-title[_ngcontent-jks-7] {
    color: #3b5998;
    font-size: 20px;
    text-align: center;
    **height: auto;**
}

![posts-title](https://cloud.githubusercontent.com/assets/17341325/21254927/761d6c74-c371-11e6-91bd-3ae455200dd6.jpg)

**Comment by nirgn975** [comment]
@yemergy What did you changed here? just the `height` attribute? (what it was before?)
Did you look at the title when you enter to the post (to check it didn't break because of that change? we need to check it because we don't have tests yet).

**Comment by nirgn975** [comment]
Fixed
