### ISSUE TITLE
Facebook like and share main buttons.

### ISSUE THREAD

**Issue by nirgn975** [nirgn975/WhatsBuzz#19]
![selection_003](https://cloud.githubusercontent.com/assets/3472902/14794093/dc45b5e2-0b2a-11e6-92d4-56b1746f0f75.png)

**Comment by nirgn975** [comment]
@yemergy What I need to write in the `title` and `description`?
And, do you want to add an image to that share button?

**Comment by yemergy** [comment]
Title: WhatsBuzz
Description: כל מה שויראלי, כל מה שבאזז אצלכם בניוז פיד. מתעדכן כל יום, כל היום
![share-img](https://cloud.githubusercontent.com/assets/17341325/14808849/5e221a5e-0b91-11e6-8a4c-f5cdbda00eb1.jpg)
