### ISSUE TITLE
Fix favicon

### ISSUE THREAD

**Issue by nirgn975** [nirgn975/WhatsBuzz#3]

**Comment by yemergy** [comment]
32x32

![logo-32x32](https://cloud.githubusercontent.com/assets/17341325/14763308/68f0ae08-099a-11e6-98f8-804d455ee409.png)

**Comment by nirgn975** [comment]
@yemergy It's live, please check.

**Comment by yemergy** [comment]
Can we try this one?

![favicon_32](https://cloud.githubusercontent.com/assets/17341325/14770096/b9c7b808-0a71-11e6-8bfa-8cec7a74ae98.jpg)
