### ISSUE TITLE
Smaller buzz title.

### ISSUE THREAD

**Issue by nirgn975** [nirgn975/WhatsBuzz#4]
![selection_001](https://cloud.githubusercontent.com/assets/3472902/14762367/36d65832-0981-11e6-9af8-e2e2d5c51daa.png)

Make the title text in buzz section like "תיבת הצעות" size.

**Comment by nirgn975** [comment]
@yemergy It's live, please check if it's O.K.

**Comment by yemergy** [comment]
![ss](https://cloud.githubusercontent.com/assets/17341325/14770146/cab0f55c-0a72-11e6-9288-76369f8b3aea.jpg)
